### ISSUE TITLE
Enable e2e test in the project

### ISSUE THREAD

**Issue by vnazarchukGD** [vnazarchukGD/ap-lab-2#2]
After migrating to the latest angular version, e2e tests configuration was broken. Please fix it and make sure all e2e tests run as intended.

**Comment by smiduthuri2** [comment]
As the project is updated to Angular 15, we need to have external test builder, hence need to use cypress/Nightwatch/WeddriverIO and run the tests. Need to discuss regarding the approach.

**Comment by smiduthuri2** [comment]
created e2e test cases using cypress
